language: elixir
elixir:
  - 1.6.1
otp_release:
  - 20.2
dist: trusty
sudo: false
services: true

cache:
  directories:
    - _build
    - deps

before_install: true

before_script:
  - mix local.hex --force
  - mix deps.get --only test
  - mix deps.clean --unused
  - MIX_ENV=test mix compile --warnings-as-errors
  - MIX_ENV=test travis_wait mix dialyzer --plt

script:
 - mix test
 - MIX_ENV=test mix dialyzer --halt-exit-status

notifications:
  slack:
    rooms:
      - activeprospect:mPeaphs7nmqUqqJ0bXIIz4Bc#trustedform
    on_success: never
    on_failure: always
